### ISSUE TITLE
ModuleNotFoundError: No module named 'src.mlproject'

### ISSUE THREAD

**Issue by Makorg123** [krishnaik06/mlprojecthindi#1]
Traceback (most recent call last):
  File "app.py", line 1, in <module>
    from src.mlproject.logger import logging
ModuleNotFoundError: No module named 'src.mlproject'

**Comment by aakashsyadav1999** [comment]
Please view you are in right directory. While cloning you may have created new folder of mlprojecthindi you have to change directory into that folder and after then you run your app.py for output

**Comment by aakashsyadav1999** [comment]
Traceback (most recent call last):
  File "F:\Vscode\new_ml_project\app.py", line 17, in <module>
    raise CustomException(e,sys)
src.new_ml_project.exception.CustomException: Error occured in python script name [F:\Vscode\new_ml_project\app.py] line number [13] error message[Error occured in python script name [F:\Vscode\new_ml_project\src\new_ml_project\components\data_ingestion.py] line number [28] error message['DataIngestion' object has no attribute 'ingestion_config']]


can anyone help me with this cause i dont how this error is showing as i have ingestion_config in DataIngestion.
