### ISSUE TITLE
not able to find the csv dataset file.

### ISSUE THREAD

**Issue by ankurpatel-india** [krishnaik06/mlprojecthindi#3]
I am not able to find the student csv dataset file. Can it be provided here?

**Comment by samagra44** [comment]
You can find the dataset in Sir's English YouTube channel in the playlist of 7 days end to end ML project. 
Here is the link - https://github.com/krishnaik06/mlproject/tree/main/notebook/data

**Comment by samagra44** [comment]
> I am not able to find the student csv dataset file. Can it be provided here?

You can find the dataset in Sir's English YouTube channel in the playlist of 7 days end to end ML project. 
Here is the link - https://github.com/krishnaik06/mlproject/tree/main/notebook/data

**Comment by ankurpatel-india** [comment]
Thanks @samagra44
